name: Simple Website

on:
  push: 
    branches:
      - front
  pull_request: 
    branches: 
      - front

jobs: 
  serve: 
    runs-on: self-hosted 
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js 
      uses: actions/setup-node@v2
      with: 
            node-version: '16'

    - name: Install HTTP server 
      run: npm install -g http-server


    - name: Serve Website
      run: http-server ./ -p 8080 