name: Simple Website

on:
  push: 
    branches:
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  serve: 
    runs-on: self-hosted 
    steps: 
    - name: Serve Website
      run: http-server ./ -p 8080 


