name: Simple Website

on:
  push: 
    branches:
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  serve: 
    runs-on: self-hosted 
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Serve Website
        run: http-server ./ -p 8080 


